/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AssistantsRouteImport } from './routes/assistants'
import { Route as CliRouteImport } from './routes/cli'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GistsRouteImport } from './routes/gists'
import { Route as GpuRouteImport } from './routes/gpu'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as NewRouteImport } from './routes/new'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PullsRouteImport } from './routes/pulls'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as StartRouteImport } from './routes/start'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as OwnerRepoRouteImport } from './routes/$owner/$repo'
import { Route as GistsIdRouteImport } from './routes/gists.$id'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoActionsRouteImport } from './routes/$owner/$repo/actions'
import { Route as OwnerRepoBranchesRouteImport } from './routes/$owner/$repo/branches'
import { Route as OwnerRepoCommitsRouteImport } from './routes/$owner/$repo/commits'
import { Route as OwnerRepoCommunityRouteImport } from './routes/$owner/$repo/community'
import { Route as OwnerRepoCompareRouteImport } from './routes/$owner/$repo/compare'
import { Route as OwnerRepoComputerRouteImport } from './routes/$owner/$repo/computer'
import { Route as OwnerRepoCreateRouteImport } from './routes/$owner/$repo/create'
import { Route as OwnerRepoDeploymentsRouteImport } from './routes/$owner/$repo/deployments'
import { Route as OwnerRepoDiscussionsRouteImport } from './routes/$owner/$repo/discussions'
import { Route as OwnerRepoForksRouteImport } from './routes/$owner/$repo/forks'
import { Route as OwnerRepoInsightsRouteImport } from './routes/$owner/$repo/insights'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner/$repo/issues'
import { Route as OwnerRepoLabelsRouteImport } from './routes/$owner/$repo/labels'
import { Route as OwnerRepoMilestonesRouteImport } from './routes/$owner/$repo/milestones'
import { Route as OwnerRepoNetworkRouteImport } from './routes/$owner/$repo/network'
import { Route as OwnerRepoPackagesRouteImport } from './routes/$owner/$repo/packages'
import { Route as OwnerRepoPreviewRouteImport } from './routes/$owner/$repo/preview'
import { Route as OwnerRepoProjectsRouteImport } from './routes/$owner/$repo/projects'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner/$repo/pulls'
import { Route as OwnerRepoReleasesRouteImport } from './routes/$owner/$repo/releases'
import { Route as OwnerRepoSecurityRouteImport } from './routes/$owner/$repo/security'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner/$repo/settings'
import { Route as OwnerRepoStargazersRouteImport } from './routes/$owner/$repo/stargazers'
import { Route as OwnerRepoTagsRouteImport } from './routes/$owner/$repo/tags'
import { Route as OwnerRepoWatchersRouteImport } from './routes/$owner/$repo/watchers'
import { Route as OwnerRepoWikiRouteImport } from './routes/$owner/$repo/wiki'
import { Route as OwnerRepoWorldRouteImport } from './routes/$owner/$repo/world'
import { Route as OwnerRepoBlameSplatRouteImport } from './routes/$owner/$repo/blame.$'
import { Route as OwnerRepoBlobSplatRouteImport } from './routes/$owner/$repo/blob.$'
import { Route as OwnerRepoEditSplatRouteImport } from './routes/$owner/$repo/edit.$'
import { Route as OwnerRepoIssuesNRouteImport } from './routes/$owner/$repo/issues.$n'
import { Route as OwnerRepoPullsNRouteImport } from './routes/$owner/$repo/pulls.$n'
import { Route as OwnerRepoTreeSplatRouteImport } from './routes/$owner/$repo/tree.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsRoute = AssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GistsRoute = GistsRouteImport.update({
  id: '/gists',
  path: '/gists',
  getParentRoute: () => rootRouteImport,
} as any)
const GpuRoute = GpuRouteImport.update({
  id: '/gpu',
  path: '/gpu',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PullsRoute = PullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const GistsIdRoute = GistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GistsRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoActionsRoute = OwnerRepoActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBranchesRoute = OwnerRepoBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitsRoute = OwnerRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommunityRoute = OwnerRepoCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCompareRoute = OwnerRepoCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoComputerRoute = OwnerRepoComputerRouteImport.update({
  id: '/computer',
  path: '/computer',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCreateRoute = OwnerRepoCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoDeploymentsRoute = OwnerRepoDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoDiscussionsRoute = OwnerRepoDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoForksRoute = OwnerRepoForksRouteImport.update({
  id: '/forks',
  path: '/forks',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoInsightsRoute = OwnerRepoInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoLabelsRoute = OwnerRepoLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoMilestonesRoute = OwnerRepoMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoNetworkRoute = OwnerRepoNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPackagesRoute = OwnerRepoPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPreviewRoute = OwnerRepoPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoProjectsRoute = OwnerRepoProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoReleasesRoute = OwnerRepoReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoSecurityRoute = OwnerRepoSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoStargazersRoute = OwnerRepoStargazersRouteImport.update({
  id: '/stargazers',
  path: '/stargazers',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoTagsRoute = OwnerRepoTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoWatchersRoute = OwnerRepoWatchersRouteImport.update({
  id: '/watchers',
  path: '/watchers',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoWikiRoute = OwnerRepoWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoWorldRoute = OwnerRepoWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBlameSplatRoute = OwnerRepoBlameSplatRouteImport.update({
  id: '/blame/$',
  path: '/blame/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBlobSplatRoute = OwnerRepoBlobSplatRouteImport.update({
  id: '/blob/$',
  path: '/blob/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoEditSplatRoute = OwnerRepoEditSplatRouteImport.update({
  id: '/edit/$',
  path: '/edit/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesNRoute = OwnerRepoIssuesNRouteImport.update({
  id: '/$n',
  path: '/$n',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoPullsNRoute = OwnerRepoPullsNRouteImport.update({
  id: '/$n',
  path: '/$n',
  getParentRoute: () => OwnerRepoPullsRoute,
} as any)
const OwnerRepoTreeSplatRoute = OwnerRepoTreeSplatRouteImport.update({
  id: '/tree/$',
  path: '/tree/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/apps': typeof AppsRoute
  '/architecture': typeof ArchitectureRoute
  '/assistants': typeof AssistantsRoute
  '/cli': typeof CliRoute
  '/cloud': typeof CloudRoute
  '/explore': typeof ExploreRoute
  '/gists': typeof GistsRouteWithChildren
  '/gpu': typeof GpuRoute
  '/issues': typeof IssuesRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/orgs': typeof OrgsRoute
  '/papers': typeof PapersRoute
  '/pricing': typeof PricingRoute
  '/pulls': typeof PullsRoute
  '/search': typeof SearchRoute
  '/stars': typeof StarsRoute
  '/start': typeof StartRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/wallet': typeof WalletRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/gists/$id': typeof GistsIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/actions': typeof OwnerRepoActionsRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/community': typeof OwnerRepoCommunityRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/computer': typeof OwnerRepoComputerRoute
  '/$owner/$repo/create': typeof OwnerRepoCreateRoute
  '/$owner/$repo/deployments': typeof OwnerRepoDeploymentsRoute
  '/$owner/$repo/discussions': typeof OwnerRepoDiscussionsRoute
  '/$owner/$repo/forks': typeof OwnerRepoForksRoute
  '/$owner/$repo/insights': typeof OwnerRepoInsightsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/labels': typeof OwnerRepoLabelsRoute
  '/$owner/$repo/milestones': typeof OwnerRepoMilestonesRoute
  '/$owner/$repo/network': typeof OwnerRepoNetworkRoute
  '/$owner/$repo/packages': typeof OwnerRepoPackagesRoute
  '/$owner/$repo/preview': typeof OwnerRepoPreviewRoute
  '/$owner/$repo/projects': typeof OwnerRepoProjectsRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/releases': typeof OwnerRepoReleasesRoute
  '/$owner/$repo/security': typeof OwnerRepoSecurityRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/stargazers': typeof OwnerRepoStargazersRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/$owner/$repo/watchers': typeof OwnerRepoWatchersRoute
  '/$owner/$repo/wiki': typeof OwnerRepoWikiRoute
  '/$owner/$repo/world': typeof OwnerRepoWorldRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/edit/$': typeof OwnerRepoEditSplatRoute
  '/$owner/$repo/issues/$n': typeof OwnerRepoIssuesNRoute
  '/$owner/$repo/pulls/$n': typeof OwnerRepoPullsNRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/apps': typeof AppsRoute
  '/architecture': typeof ArchitectureRoute
  '/assistants': typeof AssistantsRoute
  '/cli': typeof CliRoute
  '/cloud': typeof CloudRoute
  '/explore': typeof ExploreRoute
  '/gists': typeof GistsRouteWithChildren
  '/gpu': typeof GpuRoute
  '/issues': typeof IssuesRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/orgs': typeof OrgsRoute
  '/papers': typeof PapersRoute
  '/pricing': typeof PricingRoute
  '/pulls': typeof PullsRoute
  '/search': typeof SearchRoute
  '/stars': typeof StarsRoute
  '/start': typeof StartRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/wallet': typeof WalletRoute
  '/gists/$id': typeof GistsIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/actions': typeof OwnerRepoActionsRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/community': typeof OwnerRepoCommunityRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/computer': typeof OwnerRepoComputerRoute
  '/$owner/$repo/create': typeof OwnerRepoCreateRoute
  '/$owner/$repo/deployments': typeof OwnerRepoDeploymentsRoute
  '/$owner/$repo/discussions': typeof OwnerRepoDiscussionsRoute
  '/$owner/$repo/forks': typeof OwnerRepoForksRoute
  '/$owner/$repo/insights': typeof OwnerRepoInsightsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/labels': typeof OwnerRepoLabelsRoute
  '/$owner/$repo/milestones': typeof OwnerRepoMilestonesRoute
  '/$owner/$repo/network': typeof OwnerRepoNetworkRoute
  '/$owner/$repo/packages': typeof OwnerRepoPackagesRoute
  '/$owner/$repo/preview': typeof OwnerRepoPreviewRoute
  '/$owner/$repo/projects': typeof OwnerRepoProjectsRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/releases': typeof OwnerRepoReleasesRoute
  '/$owner/$repo/security': typeof OwnerRepoSecurityRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/stargazers': typeof OwnerRepoStargazersRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/$owner/$repo/watchers': typeof OwnerRepoWatchersRoute
  '/$owner/$repo/wiki': typeof OwnerRepoWikiRoute
  '/$owner/$repo/world': typeof OwnerRepoWorldRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/edit/$': typeof OwnerRepoEditSplatRoute
  '/$owner/$repo/issues/$n': typeof OwnerRepoIssuesNRoute
  '/$owner/$repo/pulls/$n': typeof OwnerRepoPullsNRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/apps': typeof AppsRoute
  '/architecture': typeof ArchitectureRoute
  '/assistants': typeof AssistantsRoute
  '/cli': typeof CliRoute
  '/cloud': typeof CloudRoute
  '/explore': typeof ExploreRoute
  '/gists': typeof GistsRouteWithChildren
  '/gpu': typeof GpuRoute
  '/issues': typeof IssuesRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/orgs': typeof OrgsRoute
  '/papers': typeof PapersRoute
  '/pricing': typeof PricingRoute
  '/pulls': typeof PullsRoute
  '/search': typeof SearchRoute
  '/stars': typeof StarsRoute
  '/start': typeof StartRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/wallet': typeof WalletRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/gists/$id': typeof GistsIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/actions': typeof OwnerRepoActionsRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/community': typeof OwnerRepoCommunityRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/computer': typeof OwnerRepoComputerRoute
  '/$owner/$repo/create': typeof OwnerRepoCreateRoute
  '/$owner/$repo/deployments': typeof OwnerRepoDeploymentsRoute
  '/$owner/$repo/discussions': typeof OwnerRepoDiscussionsRoute
  '/$owner/$repo/forks': typeof OwnerRepoForksRoute
  '/$owner/$repo/insights': typeof OwnerRepoInsightsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/labels': typeof OwnerRepoLabelsRoute
  '/$owner/$repo/milestones': typeof OwnerRepoMilestonesRoute
  '/$owner/$repo/network': typeof OwnerRepoNetworkRoute
  '/$owner/$repo/packages': typeof OwnerRepoPackagesRoute
  '/$owner/$repo/preview': typeof OwnerRepoPreviewRoute
  '/$owner/$repo/projects': typeof OwnerRepoProjectsRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/releases': typeof OwnerRepoReleasesRoute
  '/$owner/$repo/security': typeof OwnerRepoSecurityRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/stargazers': typeof OwnerRepoStargazersRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/$owner/$repo/watchers': typeof OwnerRepoWatchersRoute
  '/$owner/$repo/wiki': typeof OwnerRepoWikiRoute
  '/$owner/$repo/world': typeof OwnerRepoWorldRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/edit/$': typeof OwnerRepoEditSplatRoute
  '/$owner/$repo/issues/$n': typeof OwnerRepoIssuesNRoute
  '/$owner/$repo/pulls/$n': typeof OwnerRepoPullsNRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/apps'
    | '/architecture'
    | '/assistants'
    | '/cli'
    | '/cloud'
    | '/explore'
    | '/gists'
    | '/gpu'
    | '/issues'
    | '/marketplace'
    | '/mcp'
    | '/models'
    | '/new'
    | '/notifications'
    | '/orgs'
    | '/papers'
    | '/pricing'
    | '/pulls'
    | '/search'
    | '/stars'
    | '/start'
    | '/studio'
    | '/trending'
    | '/wallet'
    | '/$owner/$repo'
    | '/gists/$id'
    | '/topics/$slug'
    | '/$owner/'
    | '/$owner/$repo/actions'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/community'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/computer'
    | '/$owner/$repo/create'
    | '/$owner/$repo/deployments'
    | '/$owner/$repo/discussions'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/insights'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/labels'
    | '/$owner/$repo/milestones'
    | '/$owner/$repo/network'
    | '/$owner/$repo/packages'
    | '/$owner/$repo/preview'
    | '/$owner/$repo/projects'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/security'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stargazers'
    | '/$owner/$repo/tags'
    | '/$owner/$repo/watchers'
    | '/$owner/$repo/wiki'
    | '/$owner/$repo/world'
    | '/$owner/$repo/'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/edit/$'
    | '/$owner/$repo/issues/$n'
    | '/$owner/$repo/pulls/$n'
    | '/$owner/$repo/tree/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/apps'
    | '/architecture'
    | '/assistants'
    | '/cli'
    | '/cloud'
    | '/explore'
    | '/gists'
    | '/gpu'
    | '/issues'
    | '/marketplace'
    | '/mcp'
    | '/models'
    | '/new'
    | '/notifications'
    | '/orgs'
    | '/papers'
    | '/pricing'
    | '/pulls'
    | '/search'
    | '/stars'
    | '/start'
    | '/studio'
    | '/trending'
    | '/wallet'
    | '/gists/$id'
    | '/topics/$slug'
    | '/$owner'
    | '/$owner/$repo/actions'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/community'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/computer'
    | '/$owner/$repo/create'
    | '/$owner/$repo/deployments'
    | '/$owner/$repo/discussions'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/insights'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/labels'
    | '/$owner/$repo/milestones'
    | '/$owner/$repo/network'
    | '/$owner/$repo/packages'
    | '/$owner/$repo/preview'
    | '/$owner/$repo/projects'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/security'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stargazers'
    | '/$owner/$repo/tags'
    | '/$owner/$repo/watchers'
    | '/$owner/$repo/wiki'
    | '/$owner/$repo/world'
    | '/$owner/$repo'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/edit/$'
    | '/$owner/$repo/issues/$n'
    | '/$owner/$repo/pulls/$n'
    | '/$owner/$repo/tree/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/apps'
    | '/architecture'
    | '/assistants'
    | '/cli'
    | '/cloud'
    | '/explore'
    | '/gists'
    | '/gpu'
    | '/issues'
    | '/marketplace'
    | '/mcp'
    | '/models'
    | '/new'
    | '/notifications'
    | '/orgs'
    | '/papers'
    | '/pricing'
    | '/pulls'
    | '/search'
    | '/stars'
    | '/start'
    | '/studio'
    | '/trending'
    | '/wallet'
    | '/$owner/$repo'
    | '/gists/$id'
    | '/topics/$slug'
    | '/$owner/'
    | '/$owner/$repo/actions'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/community'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/computer'
    | '/$owner/$repo/create'
    | '/$owner/$repo/deployments'
    | '/$owner/$repo/discussions'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/insights'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/labels'
    | '/$owner/$repo/milestones'
    | '/$owner/$repo/network'
    | '/$owner/$repo/packages'
    | '/$owner/$repo/preview'
    | '/$owner/$repo/projects'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/security'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stargazers'
    | '/$owner/$repo/tags'
    | '/$owner/$repo/watchers'
    | '/$owner/$repo/wiki'
    | '/$owner/$repo/world'
    | '/$owner/$repo/'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/edit/$'
    | '/$owner/$repo/issues/$n'
    | '/$owner/$repo/pulls/$n'
    | '/$owner/$repo/tree/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppsRoute: typeof AppsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssistantsRoute: typeof AssistantsRoute
  CliRoute: typeof CliRoute
  CloudRoute: typeof CloudRoute
  ExploreRoute: typeof ExploreRoute
  GistsRoute: typeof GistsRouteWithChildren
  GpuRoute: typeof GpuRoute
  IssuesRoute: typeof IssuesRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  ModelsRoute: typeof ModelsRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  OrgsRoute: typeof OrgsRoute
  PapersRoute: typeof PapersRoute
  PricingRoute: typeof PricingRoute
  PullsRoute: typeof PullsRoute
  SearchRoute: typeof SearchRoute
  StarsRoute: typeof StarsRoute
  StartRoute: typeof StartRoute
  StudioRoute: typeof StudioRoute
  TrendingRoute: typeof TrendingRoute
  WalletRoute: typeof WalletRoute
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
  TopicsSlugRoute: typeof TopicsSlugRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants': {
      id: '/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gists': {
      id: '/gists'
      path: '/gists'
      fullPath: '/gists'
      preLoaderRoute: typeof GistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpu': {
      id: '/gpu'
      path: '/gpu'
      fullPath: '/gpu'
      preLoaderRoute: typeof GpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulls': {
      id: '/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof PullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gists/$id': {
      id: '/gists/$id'
      path: '/$id'
      fullPath: '/gists/$id'
      preLoaderRoute: typeof GistsIdRouteImport
      parentRoute: typeof GistsRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/actions': {
      id: '/$owner/$repo/actions'
      path: '/actions'
      fullPath: '/$owner/$repo/actions'
      preLoaderRoute: typeof OwnerRepoActionsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/branches': {
      id: '/$owner/$repo/branches'
      path: '/branches'
      fullPath: '/$owner/$repo/branches'
      preLoaderRoute: typeof OwnerRepoBranchesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commits': {
      id: '/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/commits'
      preLoaderRoute: typeof OwnerRepoCommitsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/community': {
      id: '/$owner/$repo/community'
      path: '/community'
      fullPath: '/$owner/$repo/community'
      preLoaderRoute: typeof OwnerRepoCommunityRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/compare': {
      id: '/$owner/$repo/compare'
      path: '/compare'
      fullPath: '/$owner/$repo/compare'
      preLoaderRoute: typeof OwnerRepoCompareRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/computer': {
      id: '/$owner/$repo/computer'
      path: '/computer'
      fullPath: '/$owner/$repo/computer'
      preLoaderRoute: typeof OwnerRepoComputerRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/create': {
      id: '/$owner/$repo/create'
      path: '/create'
      fullPath: '/$owner/$repo/create'
      preLoaderRoute: typeof OwnerRepoCreateRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/deployments': {
      id: '/$owner/$repo/deployments'
      path: '/deployments'
      fullPath: '/$owner/$repo/deployments'
      preLoaderRoute: typeof OwnerRepoDeploymentsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/discussions': {
      id: '/$owner/$repo/discussions'
      path: '/discussions'
      fullPath: '/$owner/$repo/discussions'
      preLoaderRoute: typeof OwnerRepoDiscussionsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/forks': {
      id: '/$owner/$repo/forks'
      path: '/forks'
      fullPath: '/$owner/$repo/forks'
      preLoaderRoute: typeof OwnerRepoForksRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/insights': {
      id: '/$owner/$repo/insights'
      path: '/insights'
      fullPath: '/$owner/$repo/insights'
      preLoaderRoute: typeof OwnerRepoInsightsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/labels': {
      id: '/$owner/$repo/labels'
      path: '/labels'
      fullPath: '/$owner/$repo/labels'
      preLoaderRoute: typeof OwnerRepoLabelsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/milestones': {
      id: '/$owner/$repo/milestones'
      path: '/milestones'
      fullPath: '/$owner/$repo/milestones'
      preLoaderRoute: typeof OwnerRepoMilestonesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/network': {
      id: '/$owner/$repo/network'
      path: '/network'
      fullPath: '/$owner/$repo/network'
      preLoaderRoute: typeof OwnerRepoNetworkRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/packages': {
      id: '/$owner/$repo/packages'
      path: '/packages'
      fullPath: '/$owner/$repo/packages'
      preLoaderRoute: typeof OwnerRepoPackagesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/preview': {
      id: '/$owner/$repo/preview'
      path: '/preview'
      fullPath: '/$owner/$repo/preview'
      preLoaderRoute: typeof OwnerRepoPreviewRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/projects': {
      id: '/$owner/$repo/projects'
      path: '/projects'
      fullPath: '/$owner/$repo/projects'
      preLoaderRoute: typeof OwnerRepoProjectsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/releases': {
      id: '/$owner/$repo/releases'
      path: '/releases'
      fullPath: '/$owner/$repo/releases'
      preLoaderRoute: typeof OwnerRepoReleasesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/security': {
      id: '/$owner/$repo/security'
      path: '/security'
      fullPath: '/$owner/$repo/security'
      preLoaderRoute: typeof OwnerRepoSecurityRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/stargazers': {
      id: '/$owner/$repo/stargazers'
      path: '/stargazers'
      fullPath: '/$owner/$repo/stargazers'
      preLoaderRoute: typeof OwnerRepoStargazersRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/tags': {
      id: '/$owner/$repo/tags'
      path: '/tags'
      fullPath: '/$owner/$repo/tags'
      preLoaderRoute: typeof OwnerRepoTagsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/watchers': {
      id: '/$owner/$repo/watchers'
      path: '/watchers'
      fullPath: '/$owner/$repo/watchers'
      preLoaderRoute: typeof OwnerRepoWatchersRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/wiki': {
      id: '/$owner/$repo/wiki'
      path: '/wiki'
      fullPath: '/$owner/$repo/wiki'
      preLoaderRoute: typeof OwnerRepoWikiRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/world': {
      id: '/$owner/$repo/world'
      path: '/world'
      fullPath: '/$owner/$repo/world'
      preLoaderRoute: typeof OwnerRepoWorldRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blame/$': {
      id: '/$owner/$repo/blame/$'
      path: '/blame/$'
      fullPath: '/$owner/$repo/blame/$'
      preLoaderRoute: typeof OwnerRepoBlameSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blob/$': {
      id: '/$owner/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$owner/$repo/blob/$'
      preLoaderRoute: typeof OwnerRepoBlobSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/edit/$': {
      id: '/$owner/$repo/edit/$'
      path: '/edit/$'
      fullPath: '/$owner/$repo/edit/$'
      preLoaderRoute: typeof OwnerRepoEditSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues/$n': {
      id: '/$owner/$repo/issues/$n'
      path: '/$n'
      fullPath: '/$owner/$repo/issues/$n'
      preLoaderRoute: typeof OwnerRepoIssuesNRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/pulls/$n': {
      id: '/$owner/$repo/pulls/$n'
      path: '/$n'
      fullPath: '/$owner/$repo/pulls/$n'
      preLoaderRoute: typeof OwnerRepoPullsNRouteImport
      parentRoute: typeof OwnerRepoPullsRoute
    }
    '/$owner/$repo/tree/$': {
      id: '/$owner/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$owner/$repo/tree/$'
      preLoaderRoute: typeof OwnerRepoTreeSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
  }
}

interface GistsRouteChildren {
  GistsIdRoute: typeof GistsIdRoute
}

const GistsRouteChildren: GistsRouteChildren = {
  GistsIdRoute: GistsIdRoute,
}

const GistsRouteWithChildren = GistsRoute._addFileChildren(GistsRouteChildren)

interface OwnerRepoIssuesRouteChildren {
  OwnerRepoIssuesNRoute: typeof OwnerRepoIssuesNRoute
}

const OwnerRepoIssuesRouteChildren: OwnerRepoIssuesRouteChildren = {
  OwnerRepoIssuesNRoute: OwnerRepoIssuesNRoute,
}

const OwnerRepoIssuesRouteWithChildren = OwnerRepoIssuesRoute._addFileChildren(
  OwnerRepoIssuesRouteChildren,
)

interface OwnerRepoPullsRouteChildren {
  OwnerRepoPullsNRoute: typeof OwnerRepoPullsNRoute
}

const OwnerRepoPullsRouteChildren: OwnerRepoPullsRouteChildren = {
  OwnerRepoPullsNRoute: OwnerRepoPullsNRoute,
}

const OwnerRepoPullsRouteWithChildren = OwnerRepoPullsRoute._addFileChildren(
  OwnerRepoPullsRouteChildren,
)

interface OwnerRepoRouteChildren {
  OwnerRepoActionsRoute: typeof OwnerRepoActionsRoute
  OwnerRepoBranchesRoute: typeof OwnerRepoBranchesRoute
  OwnerRepoCommitsRoute: typeof OwnerRepoCommitsRoute
  OwnerRepoCommunityRoute: typeof OwnerRepoCommunityRoute
  OwnerRepoCompareRoute: typeof OwnerRepoCompareRoute
  OwnerRepoComputerRoute: typeof OwnerRepoComputerRoute
  OwnerRepoCreateRoute: typeof OwnerRepoCreateRoute
  OwnerRepoDeploymentsRoute: typeof OwnerRepoDeploymentsRoute
  OwnerRepoDiscussionsRoute: typeof OwnerRepoDiscussionsRoute
  OwnerRepoForksRoute: typeof OwnerRepoForksRoute
  OwnerRepoInsightsRoute: typeof OwnerRepoInsightsRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRouteWithChildren
  OwnerRepoLabelsRoute: typeof OwnerRepoLabelsRoute
  OwnerRepoMilestonesRoute: typeof OwnerRepoMilestonesRoute
  OwnerRepoNetworkRoute: typeof OwnerRepoNetworkRoute
  OwnerRepoPackagesRoute: typeof OwnerRepoPackagesRoute
  OwnerRepoPreviewRoute: typeof OwnerRepoPreviewRoute
  OwnerRepoProjectsRoute: typeof OwnerRepoProjectsRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRouteWithChildren
  OwnerRepoReleasesRoute: typeof OwnerRepoReleasesRoute
  OwnerRepoSecurityRoute: typeof OwnerRepoSecurityRoute
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRoute
  OwnerRepoStargazersRoute: typeof OwnerRepoStargazersRoute
  OwnerRepoTagsRoute: typeof OwnerRepoTagsRoute
  OwnerRepoWatchersRoute: typeof OwnerRepoWatchersRoute
  OwnerRepoWikiRoute: typeof OwnerRepoWikiRoute
  OwnerRepoWorldRoute: typeof OwnerRepoWorldRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoBlameSplatRoute: typeof OwnerRepoBlameSplatRoute
  OwnerRepoBlobSplatRoute: typeof OwnerRepoBlobSplatRoute
  OwnerRepoEditSplatRoute: typeof OwnerRepoEditSplatRoute
  OwnerRepoTreeSplatRoute: typeof OwnerRepoTreeSplatRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoActionsRoute: OwnerRepoActionsRoute,
  OwnerRepoBranchesRoute: OwnerRepoBranchesRoute,
  OwnerRepoCommitsRoute: OwnerRepoCommitsRoute,
  OwnerRepoCommunityRoute: OwnerRepoCommunityRoute,
  OwnerRepoCompareRoute: OwnerRepoCompareRoute,
  OwnerRepoComputerRoute: OwnerRepoComputerRoute,
  OwnerRepoCreateRoute: OwnerRepoCreateRoute,
  OwnerRepoDeploymentsRoute: OwnerRepoDeploymentsRoute,
  OwnerRepoDiscussionsRoute: OwnerRepoDiscussionsRoute,
  OwnerRepoForksRoute: OwnerRepoForksRoute,
  OwnerRepoInsightsRoute: OwnerRepoInsightsRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRouteWithChildren,
  OwnerRepoLabelsRoute: OwnerRepoLabelsRoute,
  OwnerRepoMilestonesRoute: OwnerRepoMilestonesRoute,
  OwnerRepoNetworkRoute: OwnerRepoNetworkRoute,
  OwnerRepoPackagesRoute: OwnerRepoPackagesRoute,
  OwnerRepoPreviewRoute: OwnerRepoPreviewRoute,
  OwnerRepoProjectsRoute: OwnerRepoProjectsRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRouteWithChildren,
  OwnerRepoReleasesRoute: OwnerRepoReleasesRoute,
  OwnerRepoSecurityRoute: OwnerRepoSecurityRoute,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRoute,
  OwnerRepoStargazersRoute: OwnerRepoStargazersRoute,
  OwnerRepoTagsRoute: OwnerRepoTagsRoute,
  OwnerRepoWatchersRoute: OwnerRepoWatchersRoute,
  OwnerRepoWikiRoute: OwnerRepoWikiRoute,
  OwnerRepoWorldRoute: OwnerRepoWorldRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoBlameSplatRoute: OwnerRepoBlameSplatRoute,
  OwnerRepoBlobSplatRoute: OwnerRepoBlobSplatRoute,
  OwnerRepoEditSplatRoute: OwnerRepoEditSplatRoute,
  OwnerRepoTreeSplatRoute: OwnerRepoTreeSplatRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppsRoute: AppsRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssistantsRoute: AssistantsRoute,
  CliRoute: CliRoute,
  CloudRoute: CloudRoute,
  ExploreRoute: ExploreRoute,
  GistsRoute: GistsRouteWithChildren,
  GpuRoute: GpuRoute,
  IssuesRoute: IssuesRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  ModelsRoute: ModelsRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  OrgsRoute: OrgsRoute,
  PapersRoute: PapersRoute,
  PricingRoute: PricingRoute,
  PullsRoute: PullsRoute,
  SearchRoute: SearchRoute,
  StarsRoute: StarsRoute,
  StartRoute: StartRoute,
  StudioRoute: StudioRoute,
  TrendingRoute: TrendingRoute,
  WalletRoute: WalletRoute,
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
  TopicsSlugRoute: TopicsSlugRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
